import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "./ReactQueryPrivider";
import ToastProvider from "./ToastifyProvider";
import NavBar from "@/Components/Navbar/Navbar";
const vazir = Vazirmatn({
  subsets: ["arabic", "latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={vazir.className}>
        <ToastProvider>
          <ReactQueryProvider>
            <NavBar />
            {children}
          </ReactQueryProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
